<a href="https://colab.research.google.com/github/mts-machines-learn/ml-course-intro-spring2020/blob/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/001_DS_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Библиотеки для DataScience: Numpy, Matplotlib и Pandas.

# Вектор. Теория

Вектором называется направленный отрезок, для которого указано его начало и конец. Направление принято указывать стрелкой.

Рассмотрим пример вектора на плоскости. Координаты данного вектора: $(2, 3)$

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/vector1.png)


Тот же самый вектор $(2,3)$, который отложен не от начала координат, а от точки $(2,1)$

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/vector2.png)

Аналогично выглядят векторы в трехмерном пространстве. Единичные векторы принято обозночать буквами $i, j, k$.


![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/vector3.jpg)

$\bar{p} = x\bar{i} + y\bar{j} + z\bar{k} $


В общем виде вектор размерности $n$ записывается как 
$\bar{x} = \begin{pmatrix}
  x_1 \\
  x_2 \\
  \vdots \\
  x_n \end{pmatrix}$




## Операции над векторами



### Сложение, умножение вектора и скаляра

$\begin{pmatrix}
  1 \\
  2 \\
  3 \end{pmatrix} + 4  = \begin{pmatrix}
  1 + 4 \\
  2 + 4\\
  3 + 4 \end{pmatrix} = \begin{pmatrix}
  5 \\
  6 \\
  7 \end{pmatrix}$


$\begin{pmatrix}
  1 \\
  2 \\
  3 \end{pmatrix} \times 4  = \begin{pmatrix}
  1 \times 4 \\
  2 \times 4\\
  3 \times 4 \end{pmatrix} = \begin{pmatrix}
  4 \\
  8 \\
  12 \end{pmatrix}$

  Вычитание, умножение и деление производятся также поэлементно.



### Сложение вектора и вектора

Векторы складываются по правилу "параллелограмма"

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/vector4.png)


$\begin{pmatrix}
  2 \\
  1 \end{pmatrix} + 
  \begin{pmatrix}
  1 \\
  3 \end{pmatrix} = \begin{pmatrix}
  3 \\
  4 \end{pmatrix}$


### Скалярное умножение двух векторов

$\bar{v} = \begin{pmatrix}
  1 \\
  2 \\
  3 \end{pmatrix}, \bar{u} =  
  \begin{pmatrix}
  3 \\
  2 \\
  1 \end{pmatrix}$ 
  
$(v, u) = v_1 \times u_1 + v_2 \times u_2 + v_3 \times u_3 = 1 \times 3 + 2 \times 2 + 3 \times 1 = 10$

  Получили скаляр, а не вектор!


# Вектор. Практика

In [0]:
import numpy as np

#### Инициализация векторов, операции с векторами

In [0]:
a = np.array([1,3,5])
b = np.array([2,4,6])

Вектор суммы a и b

In [0]:
a + b

array([ 3,  7, 11])

Сложение вектора и скаляра




In [0]:
a + 2

array([3, 5, 7])

Скалярное произведение <a,b>

In [0]:
np.dot(a, b)  # 1*2 + 3*4 + 5*6 = 2 + 12 + 30 = 44

44

In [0]:
a @ b

44

Покомпонентное умножение векторов

In [0]:
a * b

array([ 2, 12, 30])

#### Индексация

In [0]:
a = np.array([1,3,5])

Обращение ко второму элементу вектора:

In [0]:
a[2]

5

Изменение второго элемента вектора:

In [0]:
a[2] = 7

In [0]:
print(a)

[1 3 7]


Копирование вектора

In [0]:
b = a
b[2] = 10

In [0]:
print(a)

[ 1  3 10]


In [0]:
a = np.array([1,3,5])

In [0]:
b = a.copy()
b[2] = 10

In [0]:
print(a)

[1 3 5]


np.arange

In [0]:
range_50 = np.arange(100,150,1)
print(range_50)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [0]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Индексы и срезы

In [0]:
range_50[6:14]

array([106, 107, 108, 109, 110, 111, 112, 113])

In [0]:
range_50[[6,8,10,12]]

array([106, 108, 110, 112])

In [0]:
range_50[6:14:2]

array([106, 108, 110, 112])

In [0]:
range_50[::]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [0]:
range_50[::-1]

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [0]:
range_50[:10]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [0]:
range_50[:10] = 0

In [0]:
range_50

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [0]:
a = range_50[:10]
print(a)
a[:] = 1
print(a)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [0]:
range_50

array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   1, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [0]:
a = range_50[:10].copy()
print(a)
a[:] = 2
print(a)

[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [0]:
range_50

array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   1, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

### Задача 1. Создать вектор длины n из чисел вида 0, 3, 6, 9, ...

In [0]:
n = 100
range_3k = np.arange(0,n,3) 

In [0]:
range_3k

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### Задача 2. Заменить в массиве случайные k элементов на 0.


In [0]:
def random_zeros(array, k):
  random_ind = np.random.choice(np.arange(len(array)), size=k, replace=False)
  print(np.sort(random_ind))
  array[random_ind] = 0
  return array

In [0]:
random_zeros(np.array([1,2,3,4,5,6,7,8,9,10]), 5)

[0 1 4 8 9]


array([0, 0, 3, 4, 0, 6, 7, 8, 0, 0])

### Функции агрегирования для вектора

In [0]:
inflation = np.array([8.78, 6.1, 6.58, 6.45, 11.36, 12.91, 5.38, 2.52, 4.27, 2.68])

In [0]:
inflation.max()

12.91

In [0]:
inflation.min()

2.52

In [0]:
inflation.mean()

6.703

In [0]:
marks = np.array([3,3,4,5,5,4,2,4,4,4,4,5])

In [0]:
marks.mean()

3.9166666666666665

In [0]:
marks.sum()

47

In [0]:
np.median(marks)

4.0

### Задача 3. Посчитать сумму первых k элементов вектора

In [0]:
def first_k_sum(array, k):
  return array[:k].sum()

In [0]:
first_k_sum(np.array([1,1,1,1,1,1,1,1,1,1]), 7)

7

# Матрицы. Теория

Матрица - обычно это набор чисел, упорядоченных по строкам и столбцам.

Примеры:

$A_{3,3} =
 \begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix}$ , 

$A_{2,3} =
 \begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  \end{pmatrix}$, 

$A_{3,2} =
 \begin{pmatrix}
  1 & 2 \\
  4 & 5 \\
  7 & 8  \\
  \end{pmatrix}$ , 

Общий вид: 

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $m$ - количество строк матрицы

 $n$ - количество столбцов матрицы

 $a_{i,j}$ - элемент, стоящий на пересечении $i$-той строки и $j$-го столбца



## Операции над матрицами




### Сложение, умножение матрицы и скаляра:

$\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix} + 2 = \begin{pmatrix}
  1+2 & 2+2 & 3+2 \\
  4+2 & 5+2 & 6+2 \\
  7+2 & 8+2 & 9+2  \\
  \end{pmatrix} =
  \begin{pmatrix}
  3 & 4 & 5 \\
  6 & 7 & 8 \\
  9 & 10 & 11  \\
  \end{pmatrix}$


$\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix} \times 2 = \begin{pmatrix}
  1\times2 & 2\times2 & 3\times2 \\
  4\times2 & 5\times2 & 6\times2 \\
  7\times2 & 8\times2 & 9\times2  \\
  \end{pmatrix} = \begin{pmatrix}
  2 & 4 & 6 \\
  8 & 10 & 12 \\
  14 & 16 & 18  \\
  \end{pmatrix}$




### Cложение матриц 

(складываем матрицы с одинаковыми размерами)

$\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix} +  \begin{pmatrix}
  3 & 3 & 3 \\
  1 & 1 & 1 \\
  2 & 2 & 2  \\
  \end{pmatrix} = \begin{pmatrix}
  1+3 & 2+3 & 3+3 \\
  4+1 & 5+1 & 6+1 \\
  7+2 & 8+2 & 9+2  \\
  \end{pmatrix} = \begin{pmatrix}
  4 & 5 & 6 \\
  5 & 6 & 7 \\
  9 & 10 & 11 \\
  \end{pmatrix}$

 ### Умножение матрицы на вектор

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/matrix_1.PNG)

<!-- 
$\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix} \times \begin{pmatrix}
  1  \\
  2 \\
  3 \\
  \end{pmatrix} = \begin{pmatrix}
  1\times1+2\times2+3\times3 \\
  4\times1+5\times2+6\times3 \\
  7\times1+8\times2+9\times3
  \end{pmatrix} = \begin{pmatrix}
  14 \\
  32 \\
  50
  \end{pmatrix}$ -->

 


 ### Умножение матрицы на матрицу

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/matrix_2.PNG)

 <!-- $\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9  \\
  \end{pmatrix} \times \begin{pmatrix}
  1 & 2\\
  2 & 0\\
  3 & 1\\
  \end{pmatrix} = \begin{pmatrix}
  1\times1+2\times2+3\times3 & 1\times2 + 2\times0 + 3\times1 \\
  4\times1+5\times2+6\times3 & 4\times2 + 5\times0 + 6\times1 \\
  7\times1+8\times2+9\times3 & 7\times2 + 8\times0 + 9\times1 \\
  \end{pmatrix} = \begin{pmatrix}
  14 & 5 \\
  32 & 14 \\
  50 & 23 \\
  \end{pmatrix}$ -->

Как изменяются размерности матриц?


![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/matrix_3.jpg)

$A_{n,k} \times B_{k,m} = C_{n,m}$ (количество столбцов в первой матрице равно количеству строк во второй матрице)

Тогда элементы матрицы произведения определяются как:

$C_{i,j} = \sum_k{A_{i,k}B_{k,j}}$


### Транспонирование матрицы

  $B = \begin{pmatrix}
  1 & 2 \\
  4 & 5 \\
  7 & 8 \\
  \end{pmatrix} B^T = \begin{pmatrix}
  1 & 4 & 7 \\
  2 & 5 & 8 \\
  \end{pmatrix}$

Для элементов матриц $B$ и $B^T$ выполнено следующее: 
$B_{i,j} = B^T_{j.i}$

  Если размерность матрицы $B = (m,n)$, то рамерность матрицы $B^T = (n,m)$

# Матрицы. Практика

##### Инициализация матриц, операции с матрицами

In [0]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[3,3,3],
              [1,1,1],
              [2,2,2]])

Сумма двух матриц

In [0]:
A + B

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 9, 10, 11]])

Сумма матрицы и скаляра

In [0]:
A + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Произведение матрицы и скаляра

In [0]:
A * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [0]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([1,2,3])

Произведение матрицы и вектора

In [0]:
A @ v

array([14, 32, 50])

In [0]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1,2],
              [2,0],
              [3,1]])

Произведение матриц

In [0]:
A @ B

array([[14,  5],
       [32, 14],
       [50, 23]])

shape

In [0]:
A = np.array([1,2,3,4,5,6])

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/matrix_4.jpg)

In [0]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
A.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
A = A.reshape(-1, 3)

In [0]:
A.shape

(2, 3)

In [0]:
A.size

6

##### Размерности матриц

![](https://raw.githubusercontent.com/mts-machines-learn/ml-course-intro-spring2020/lesson3/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/images/axis.jpg)

In [0]:
A = np.array([[2,3,4,5],
              [6,7,8,9]])

In [0]:
A.sum()

In [0]:
A.sum(axis=0)


In [0]:
A.sum(axis=1)

##### Задача 4: Создать матрицу из четных чисел, размера m*n;

In [0]:
def create_odd_matrix_way1(m,n):
  size = m*n
  array = np.arange(0, 2*size, 2)
  array = array.reshape(m, n)
  return array

In [0]:
create_odd_matrix_way1(4,3)

#### Индексация

In [0]:
A = np.arange(0, 25)

In [0]:
A = A.reshape(5,5)
A

Обращение к строке матрицы

In [0]:

A[2]

Обращение к столбцу матрицы

In [0]:

A[:, 2]

Обращение к элементу матрицы

In [0]:
A[2, 2]

Срезы матрицы

In [0]:
A[0:3, 0:3]

In [0]:
A[0:3, 0:3] = 100

In [0]:
A

In [0]:
A[2] = 50

In [0]:
A

In [0]:
A[1] = np.array([10, 20, 30, 40, 50])

In [0]:
A

#### Матрицы из нулей, единиц

In [0]:
np.ones((4,5))

In [0]:
np.zeros((4,5))

#### Задача 5. Создать матрицу с элементами вида $a_{i,j} = i$

То есть все значения в строке одинаковы и равны номеру строки

Вид матрицы размера $(4,4)$: 

$\begin{pmatrix}
0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1\\
2&2&2&2\\
3&3&3&3
\end{pmatrix}$

In [0]:
def create_rows_matrix(n,m):
  array = np.zeros((n,m))
  for i in range(n):
    array[i] = i
  return array

In [0]:
create_rows_matrix(3,5)

In [0]:
def create_columns_matrix(n,m):
  array = np.zeros((n,m))
  for j in range(m):
    array[:, j] = j
  return array

In [0]:
create_columns_matrix(3,5)

#### Задача 6. Создать матрицу $A_{n,m}$ со сдвигом в строках.

Вид матрицы размера $(4,4)$: 

$\begin{pmatrix}
0 & 1 & 2 & 3 \\
1 &2&3&4\\
2&3&4&5\\
3&4&5&6
\end{pmatrix}$

In [0]:
def shift_matrix(n, m):
  array = np.zeros((n,m))
  for i in range(n):
    array[i] = np.arange(i, m+i)
  return array.reshape(n,m) 

In [0]:
shift_matrix(5,6)

#### Конкатенация матриц по строкам и столбцам

In [0]:
A = np.array([[1,2,3], 
              [4,5,6]])
B = np.array([[7,8,9],
               [10,11,12]])

In [0]:
C = np.vstack((A, B))
C

In [0]:
D = np.hstack((A, B))
D

### Задача 7. Для квадратной матрицы $A$ создать блочную матрицу вида
 $\begin{bmatrix}
A & A^T
 \end{bmatrix}$. (Конкатенация двух матриц)

In [0]:
def concat_transpose(A):
  assert A.shape[0] == A.shape[1]

  return np.hstack((A, A.T))

In [0]:
A = np.array([[3,4,5],
              [1,2,3],
              [3,4,2]])

In [0]:
concat_transpose(A)

# Функции

функция одной переменной

In [0]:
x = 4

In [0]:
np.sqrt(x)

функция от вектора

In [0]:
squares_vec = np.array([1,4,9,16,25])

In [0]:
np.sqrt(squares_vec)

In [0]:
x**2

In [0]:
squares_vec**2

In [0]:
def rub2usd(x):
  return x / 63.54


In [0]:
rub2usd(2000)

In [0]:
items = np.array([2000,2500,3534,3000,3200])

In [0]:
rub2usd(items)

In [0]:
shop = np.array([[6500,3000,3500,4000,2000],
                  [5200,3000,1500,4000,3000]])

In [0]:
rub2usd(shop)

# Графики функций

http://matplotlib.org/gallery.html

In [0]:
import matplotlib.pyplot as plt

In [0]:
inflation = np.array([8.78, 6.1, 6.58, 6.45, 11.36, 12.91, 5.38, 2.52, 4.27, 2.68])
years = np.arange(2010, 2020)

In [0]:
years

In [0]:
plt.figure(figsize=(6, 4))
plt.scatter(years, inflation, label='inflation', marker='o')
plt.legend()
plt.show()

In [0]:
plt.figure(figsize=(6, 4))
plt.plot(years, inflation)
plt.show()

In [0]:
plt.figure(figsize=(6, 4))
plt.plot(years, inflation, marker='o', color='black')
plt.xlabel('Год')
plt.ylabel('Инфляция')
plt.show()

In [0]:
day_temp = np.array([-2, -5, -7, -8, -8, -10, -10, -9, -8, -7, -6, -5, -3, -3, -4, -5, -7, -8, -8,
                     -8, -9, -9, -8, -8, -9, -10, -8, -7, -7, -7, -6])
night_temp = np.array([-6, -6, -9, -9, -11, -11, -11, -9, -9, -8, -7, -5, -4, -5, -6, -7, -9, -10, 
                       -10, -10, -11, -9, -9, -10, -12, -11, -9, -9, -9, -8, -8])

In [0]:
plt.figure(figsize=(10, 4))
plt.plot(day_temp, color='red', label='дневная температура')
plt.plot(night_temp, color='blue', label='ночная температура')
plt.fill_between(x=np.arange(31), y1=night_temp, y2=day_temp, alpha=0.5)
plt.xlabel('День января')
plt.ylabel('Температура')
plt.legend()
plt.show()

In [0]:
x = np.arange(-2*np.pi, 2*np.pi, 0.01)

In [0]:
plt.figure(figsize=(10, 4))
plt.plot(x, np.sin(x), color='red', label='$\sin{x}$')
plt.plot(x, np.cos(x), color='blue', label='$\cos{x}$')
plt.plot(x, np.cos(x + np.pi/2), color='green', dashes=[2, 1], label='$\cos{(x+\\frac{\pi}{2})}$')
plt.xlabel('x')
plt.legend(loc='upper left')
plt.show()

In [0]:
x = np.arange(0, 2, 0.01)

plt.figure(figsize=(6,4))
plt.plot(x, x, x, x**2, x, x**3)
plt.show()

# Диаграммы


In [0]:
marks = np.array([3,3,4,5,5,4,2,4,4,4,4,5])

In [0]:
plt.figure(figsize=(6, 4))
plt.hist(marks, label='оценки Пети Иванова', alpha=0.5)
plt.legend(loc='upper left')
plt.show()

In [0]:
plt.figure(figsize=(6, 4))

x = np.random.normal(1, 2, 5000)
y = np.random.normal(-1, 3, 5000)
plt.hist([x, y], bins=20, label=['$N(1,2)$', '$N(-1,3)$'])
plt.legend(loc='upper right')
plt.show()

# Теория вероятностей

Будем считать случайное испытание экспериментом по измерению некоторой величины, который можно повторять много раз при фиксированных
условиях, получая при этом случайные результаты.
Для изучения берется множество
значений, которое может принимать результат такого эксперимента, и распределение вероятности
по этому множеству. Распределение вероятности можно понимать как распределение относительных частот различных результатов в серии повторных
экспериментов.
Определим случайную
величину как пару из (1) множества значений и (2) распределения вероятности по этому множеству.

## Основные свойства вероятности:

1) $0 \leq P(A) \leq 1$

2) $P(∅) = 0$

3) $P(\overline{A}) + P(A) = 1$


Для пары событий возможны следующие отношения:

### Вложенность: $A \subseteq B$

Пример: $A$ - на игральном кубике выпала 6-ка, $B$ - на игральном кубике выпало четное число

Тогда событие $A$ вложено в событие $B$

$A \subseteq B \implies P(A) \leq P(B)$

### Произведение событий $AB$ и сумма событий $A+B$.

Пример: $A$ - на игральном кубике выпало четное число, $B$ - на игральном кубике выпало число большее 3.

$AB$ - пересечение событий, то есть произошло каждое из этих событий. $AB$ = на кубике выпали числа: 4, 6.

$A+B$ - обединение событий, произошло хотя бы одно из данных событий. $A+B$ = на кубике выпали: четные числа или 5-ка

$P(A+B) = P(A) + P(B) - P(AB)$

### Дополнение: $B\setminus A$

Происходит событие B, но не происходит событие A.

$A$ - на игральном кубике выпало четное число, $B$ - на игральном кубике выпало число большее 3.

$B\setminus A$ = на игральном кубике выпало число 5.


$P(B\setminus A) = P(B) - P(AB)$, есл $A$ полностью лежит в $B$, то формула упрощается: $P(B\setminus A) = P(B) - P(A)$





### Независимость событий $A, B$

События $A, B$ являются независимыми, если вероятность их пересечения равна
произведению вероятностей компонент: $P(AB) = P(A)P(B)$

Пример: A - на кубике выпало четное число, B - на кубике выпало число большее 3, AB - на кубике выпало число 4 или 6.

$P(A) = \frac{1}{2}, P(B) = \frac{1}{2}, P(AB) = \frac{1}{3}$ - события зависимы

### Условная вероятность

$A$ - на кубике выпала цифра 5, $B$ - на кубике выпало числе большее 3. Если известно, что событие $B$ произошло, то вероятность события $A$ повышается. Условная вероятность события $A$ при условии, что произошло событие $B$, определяется следующим образом: $P(A|B) = \frac{P(AB)}{P(B)}$

$P(B) = \frac{1}{2}, P(AB) = \frac{1}{6} \implies P(A|B) = \frac{1}{3}$


## Случайные величины, виды распределений


В испытании с подбрасыванием кубика возможны шесть исходов. Эти исходы
можно пронумеровать 1, 2, 3, 4, 5, 6 согласно значению, выпавшему на кубике. Данному множеству исходов ставится в соответствие вектор вероятности:

$\{1,2,3,4,5,6\} \implies \begin{pmatrix}
  p_1 \\
  p_2 \\
  p_3 \\
  p_4 \\
  p_5 \\
  p_6 \end{pmatrix}, p_i \geq 0, \sum_{i=1}^{6}{p_i} = 1$


Дискретная случайная величина X принимает счетное
множество значений $A = \{a_1, a_2, a_3, . . . \}$ с вероятностями $p_1, p_2, p_3, . . .$

$p_i \geq 0, \sum_{i=1}^{\infty}{p_i} = 1$


Функция вероятности имеет вид: $P(X = a_i) = p_i$


Рассмотрим дискретную случайную величину с двумя исходами. Примером в данном случае является подбрасывание монеты. Можно обозначить выпадение решки за 1, а
выпадение орла — за 0. Пусть вероятность «успеха» равна $p:
P(X = 1) = p, P(X = 0) = 1 - p$.

Так устроена бернуллиевская случайная величина: $$X \sim Ber(p)$$

Рассмотрим такуже модель, только теперь мы подбрасываем монетку не один раз, а n раз.

Вероятность выпадения решки равна $p$, вероятность выпадения орла равна $1-p$. 

Случайная величина $X$  - число выпаданий решки. В силу независимости попыток: $P(X = n) = p^n$
 
В общем случае: $P(X=k) = C_n^kp^k(1-p)^{n-k}, k = 0,1,2,...,n$

Такая случайная величина X называется биномиальной.
$$X \sim Bin(n, p)$$

$Ber(p) = Bin(1, p)$

In [0]:
n, p = 1, 0.5
X_Ber = np.random.binomial(n, p, 10000)

In [0]:
plt.figure(figsize=(6, 4))

plt.hist([X_Ber], bins=30, label=['$Ber(0.5)$'])
plt.legend(loc='upper right')
plt.show()

Непрерывные случайные величины могут принимать несчетное число значений и задаются по другому:

Первый способ определения таких величин — с помощью функции распределения: $F(x) = P(X \leq x)$







Второй способ определения непрерывных случайных величин — с помощью плотности распределения:

$f(x): \int_{a}^{b}f(x)dx = P(a \leq X \leq b)$

Плотность связана с функцией распределения следующим образом:

$F(x) = \int_{-\infty}^{x}f(u)du$

Для непрерывной случайной величины верно равенство:

$\int_{-\infty}^{\infty}f(u)du = 1$


Одним из самых важных примеров непрерывной случаной величины является нормальная случайная величина. 

К примеру, Иван любит играть в дартс и почти всегда попадает в десятку, однакого иногда он может промахиваться. Точное место попадания его дротика $X$ моделируется с помощью нормального (Гауссового) распределения:

$$X \sim N(\mu, \sigma)$$


Параметр $\mu$ отвечает за среднее место попадания Ивана, а параметр $\sigma$ отвечает за разброс бросков вокруг среднего значения. 

Функция плотности нормального распределения имеет вид: 

$f(x) = \frac{1}{\sqrt{2\pi \sigma^2}} exp(-\frac{(x-\mu)^2}{2\sigma^2})$

In [0]:
mu, sigma = 0.0, 1.0
X_Norm = np.random.normal(mu, sigma, 10000)

In [0]:
np.mean(X_Norm)

In [0]:
np.std(X_Norm)

In [0]:
plt.figure(figsize=(6, 4))

plt.hist([X_Norm], bins=30, label=['$N(0,1)$'], density=True)
plt.legend(loc='upper right')
plt.show()

In [0]:
def norm_df(x, mu, sigma):
  return 1/(2*np.pi*sigma**2)**(0.5) * np.exp(-((x-mu)**2)/(2*sigma**2))

In [0]:
standart_df = norm_df(X_Norm, 0, 1)

In [0]:
plt.scatter(X_Norm, standart_df, s=0.5)
plt.show()

# Pandas

In [0]:
import pandas as pd
from sklearn.datasets import load_iris

In [0]:
data = load_iris()

In [144]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [0]:
df = pd.DataFrame(data['data'], columns=data['feature_names'])
y = pd.DataFrame(data['target'])

In [0]:
df['target'] = y

In [0]:
df.to_csv("iris.csv")

In [0]:
data['target_names']

In [0]:
df.head()

In [0]:
df.shape

In [0]:
df.info()

In [0]:
df.describe()

In [0]:
df.columns

In [0]:
df.columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [0]:
df.head()

In [0]:
df['sepal_length']

In [0]:
df.sepal_length

In [0]:
df[['sepal_length', 'sepal_width']]

In [0]:
df['index'] = np.arange(100, 250)

In [0]:
df = df.set_index('index')
df

In [0]:
df.loc[100]

In [0]:
df.iloc[0]

In [0]:
df.iloc[[2, 3], [1, 2]]

In [0]:
df.loc[120:130]

In [0]:
df.loc[120:130][['sepal_length', 'sepal_width']]

In [0]:
df.loc[df.sepal_width > 3.5, ["sepal_width", "petal_length", "petal_width"]]

In [0]:
df.loc[(df.sepal_width > 3.5) & (df.petal_width > 0.6)]

In [0]:
df['sepal_area'] = df.sepal_length * df.sepal_width

In [0]:
df

In [0]:
df = df.drop(['sepal_area'], axis=1)
df

In [0]:
df.sort_values(by='petal_length', ascending=False)

# Визуализация данных в Pandas

In [0]:
plt.scatter(df['sepal_length'], df['sepal_width'])
plt.title('Iris Dataset')
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.show()

In [0]:
df.plot.scatter(x='sepal_length', y='sepal_width', s=40, title='Iris Dataset')
plt.show()

In [0]:
colors = {0:'r', 1:'g', 2:'b'}

plt.figure(figsize=(8, 6))
for i in range(len(df['sepal_length'])):
    plt.scatter(df['sepal_length'].iloc[i], df['sepal_width'].iloc[i],color=colors[df['target'].iloc[i]])
plt.title('Iris Dataset')
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.show()

In [0]:
df.plot.scatter(x='sepal_length', y='sepal_width', title='Iris Dataset', s=40, c='target', figsize=(10,6), colormap='viridis')
plt.show()

In [0]:
df.drop('target', axis=1).plot.hist(subplots=True, layout=(2,2), figsize=(8, 8), bins=20)
plt.show()