In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from regression2_helper import * # Подгружаем функции для визуализации
import numpy as np              # Подгруджаем библиотеку NumPy

In [3]:
np.set_printoptions(formatter={'float': lambda x: format(x, '6.3f')}) # настройка вывода для матриц

In [4]:
#загрузим данные
X_room, X_lstat, y = load_small_data() 

# Линейная функция в матричном виде

Давайте вспомним как считать матричное произведение. 

## Произведение матрицы и вектор-строки на вектор-столбец

\begin{equation*}
\textbf{r} = \begin{pmatrix}
    r_{0, 0}  & \ldots & r_{0, j} \ldots r_{0, m-1} \\
\end{pmatrix}
\end{equation*}

Размер $(1, m)$.

\begin{equation*}
\textbf{c} = \begin{pmatrix}
    c_{0, 0} \\
    \ldots \\
    c_{j, 0} \\
    \ldots \\
    c_{m-1, 0}
\end{pmatrix}
\end{equation*}

Размер $(m, 1)$.

$$\textbf{r c} = \sum_{i=0}^{m-1} r_{0, i}c_{i, 0}$$

\begin{equation*}
\textbf{c} = \begin{pmatrix}
    c_{0, 0} \\
    \ldots \\
    c_{j, 0} \\
    \ldots \\
    c_{m-1, 0}
\end{pmatrix}
\end{equation*}

Размер $(m, 1)$.

Часто для удобства вектор-столбец записывают через операцию транспонирования \begin{equation*}
\textbf{c} = \begin{pmatrix}
    c_{0, 0} &
    \ldots &
    c_{0, j} &
    \ldots &
    c_{0, m-1}
\end{pmatrix}^T
\end{equation*}

## Произведение матрицы на вектор-столбец

\begin{equation*}
A = \begin{pmatrix}
    a_{0, 0} & \ldots & a_{0, j} & \ldots & a_{0, m-1} \\
    \cdot &   \cdot  & \cdot &    \cdot \\
    a_{i, 0}  & \ldots & a_{i, j} & \ldots & a_{i, m-1} \\
    \cdot &   \cdot  & \cdot &    \cdot \\
    a_{n-1, 0} & \ldots & a_{n-1, j}  & \ldots  & a_{n-1, m-1} \\
\end{pmatrix}
\end{equation*}

Размер $A = (n, m)$.

\begin{equation*}
\textbf{c} = \begin{pmatrix}
    c_{0, 0} &
    \ldots &
    c_{0, j} &
    \ldots &
    c_{0, m-1}
\end{pmatrix}^T
\end{equation*}

Размер $(m, 1)$.

\begin{equation*}
A \cdot \textbf{c} = \begin{pmatrix}
    a_{0, 0} & \ldots & a_{0, j} & \ldots & a_{0, m-1} \\
    \cdot &   \cdot  & \cdot &    \cdot \\
    a_{i, 0}  & \ldots & a_{i, j} & \ldots & a_{i, m-1} \\
    \cdot &   \cdot  & \cdot &    \cdot \\
    a_{n-1, 0} & \ldots & a_{n-1, j}  & \ldots  & a_{n-1, m-1} \\
\end{pmatrix}
\begin{pmatrix}
    с_{0, 0} \\
    \ldots \\
    с_{j, 0} \\
    \ldots \\
    с_{m-1, 0}
\end{pmatrix}
\end{equation*}

\begin{equation*}
A \cdot \textbf{c} = \begin{pmatrix}
    a_{0, 0} c_{0, 0} + \ldots + a_{0, j} c_{j, 0} + \ldots +a_{0, m-1} c_{m-1, 0} \\
    \cdots \\
    a_{i, 0} c_{0, 0} + \ldots + a_{i, j} c_{j, 0} + \ldots +a_{i, m-1} c_{m-1, 0} \\
    \cdots \\
    a_{n-1, 0} c_{0, 0} + \ldots + a_{n-1, j} c_{j, 0} + \ldots +a_{n-1, m-1} c_{m-1, 0} \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}
A \cdot \textbf{c} = \begin{pmatrix}
    a_{0, 0} c_{0, 0} + \ldots + a_{0, j} c_{j, 0} + \ldots +a_{0, m-1} c_{m-1, 0} \\
    \cdots \\
    a_{i, 0} c_{0, 0} + \ldots + a_{i, j} c_{j, 0} + \ldots +a_{i, m-1} c_{m-1, 0} \\
    \cdots \\
    a_{n-1, 0} c_{0, 0} + \ldots + a_{n-1, j} c_{j, 0} + \ldots +a_{n-1, m-1} c_{m-1, 0} \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}
A \cdot \textbf{c} =
\begin{pmatrix}
    \sum_i^{m-1} a_{0, i} c_{i, 0} \\
    \cdots \\
    \sum_i^{m-1} a_{j, i} c_{i, 0} \\
    \cdots \\
    \sum_i^{m-1} a_{n-1, i} c_{i, 0} \\
\end{pmatrix}
\end{equation*}

## Вычисление одного значения линейной функции в матричном виде

Объединим признаки для $i$-того примера в вектор стоку 
\begin{equation*}
x_i = \begin{pmatrix} x_{i, 1} & x_{i, 2}
\end{pmatrix}
\end{equation*}


$x_{i, 1}$ - это среднее количество комнат $i$-го примера.

$x_{i, 2}$ - LSTAT $i$-го примера.

Также объединим коэффициенты в вектор-столбец $\theta = \begin{pmatrix}
    \theta_1\\
    \theta_2\\
  \end{pmatrix} =  \begin{pmatrix}\theta_1 & \theta_2 \end{pmatrix}^T$

Объединив признаки и коэффициенты в вектора можем переписать предсказание $i$-того примера в матричном виде:
  

\begin{equation*}
\tilde{y}_i= \theta_0 + \begin{pmatrix}x_{i, 1} & x_{i, 2}\end{pmatrix} \begin{pmatrix}
    \theta_1\\
    \theta_2\\
  \end{pmatrix} = \theta_0 + \theta_1 x_{i, 1} + \theta_2 x_{i, 2}
\end{equation*}

$$\tilde{y}_i= \theta_0 + x_i \theta$$

Добавим к вектору $x_i$  единицу:

${X}_i = \begin{pmatrix} 1 & x_{i, 1} & x_{i, 2}\end{pmatrix}$

Добавим $\theta_0$ в вектор-столбец коэффициентов $\theta$ первым элементом:
\begin{equation*}
\Theta = \begin{pmatrix}\theta_0 &  \theta_1 & \theta_2\end{pmatrix}^T,
\end{equation*}


Вычисление предсказанной цены $\tilde{y}_i$ сведётся к матричному произведению:

\begin{equation*}
\tilde{y}_i= \begin{pmatrix} 1 & x_{i, 1} & x_{i, 2}\end{pmatrix} \begin{pmatrix}
    \theta_0\\
    \theta_1\\
    \theta_2\\
  \end{pmatrix} =  1 \cdot \theta_0 + \theta_1 x_{i, 1} + \theta_2 x_{i, 2}.
\end{equation*}

\begin{equation*}
\tilde{y}_i = X_i\Theta.
\end{equation*}

Эта формула позволяет вычислить предсказание для одного конкретного жилья в Бостоне.

Но с помощью матричного произведения можно вычислить предсказание стоимости жилья сразу для всех квартир.

Допустим у нас есть $N$ примеров в обучающей выборке $x_{i,0} = 1$. Тогда весь набор можно записать как:

\begin{equation*}
X= \begin{pmatrix}
1& x_{0,1}& x_{0,2} \\
\cdots & \cdots & \cdots \\
1& x_{i,1}& x_{i,2} \\
\cdots & \cdots & \cdots \\
1& x_{N-1,1}& x_{N-1,2} \\
\end{pmatrix}=
\begin{pmatrix}
x_{0,0}& x_{0,1}& x_{0,2} \\
\cdots & \cdots & \cdots \\
x_{i,0}& x_{i,1}& x_{i,2} \\
\cdots & \cdots & \cdots \\
x_{N-1,0}& x_{N-1,1}& x_{N-1,2} \\
\end{pmatrix}
\end{equation*}

или

\begin{equation*}
X= \begin{pmatrix}
X_0 \\
\cdots\\
X_i \\
\cdots\\
X_N-1 \\
\end{pmatrix}
\end{equation*}

Или в самом коротком виде: $X = \begin{pmatrix} X_0 & X_1 & \ldots & X_{N-1} \end{pmatrix}^T$, где $X_i = \begin{pmatrix} x_{i,0} & x_{i,1} & x_{i,2}\end{pmatrix}$.

Тогда для предсказания стоимости жилья всех квартир запишем $N$ выражений:

\begin{cases}
\tilde{y}_0 = 1\cdot \theta_0 + \theta_1 x_{0,1} + \theta_2 x_{0,2}\\
\cdots \\ 
\tilde{y}_i = 1\cdot \theta_0 + \theta_1 x_{i,1} + \theta_2 x_{i,2}\\
\cdots\\
\tilde{y}_{N-1} = 1\cdot \theta_0 + \theta_1 x_{N-1,1} + \theta_2 x_{N-1,2}\\
\end{cases}

\begin{cases}
\tilde{y}_1 = x_{0,0}\theta_0 + \theta_1 x_{0,1} + \theta_2 x_{0,2}\\
\cdots\\
\tilde{y}_i = x_{i,1}\theta_0 + \theta_1 x_{i,1} + \theta_2 x_{i,2}\\
\cdots\\
\tilde{y}_{N-1} = x_{N-1,1}\theta_0 + \theta_1 x_{N-1,1} + \theta_2 x_{N-1,2}\\
\end{cases}

Или тоже самое можно записать в матричном виде:  

\begin{equation*}
\tilde{y} =  \begin{pmatrix}
x_{0,0}& x_{0,1}& x_{0,2} \\
\cdots & \cdots & \cdots \\
x_{i,0}& x_{i,1}& x_{i,2} \\
\cdots & \cdots & \cdots \\
x_{N-1,0}& x_{N-1,1}& x_{N-1,2} \\
\end{pmatrix}\cdot
\begin{pmatrix}
    \theta_0\\
    \theta_1\\
    \theta_2
  \end{pmatrix}
\end{equation*} 
  
\begin{equation*}
\tilde{y} = \begin{pmatrix}
x_{0,0}\theta_0 + \theta_1 x_{0,1} + \theta_2 x_{0,2}\\
\cdots  \\
x_{i,0}\theta_0 + \theta_1 x_{i,1} + \theta_2 x_{i,2}\\
\cdots  \\
x_{N-1,0}\theta_0 + \theta_1 x_{N-1,1} + \theta_2 x_{N-1,2}\\
  \end{pmatrix}=
  \begin{pmatrix}
    \tilde{y}_0\\
    \cdots \\
    \tilde{y}_i\\
    \cdots \\
    \tilde{y}_{N-1}\\
  \end{pmatrix}
\end{equation*}

$x_{i, 0} = 1$  

\begin{equation*}
\tilde{y} = X\Theta.
\end{equation*}

## Реализация линейной функции с помощью матричного произведения 

Составим матрицу $X$ из наших признаков.

In [5]:
def create_data(X1, X2):
    X_ones = np.ones_like(X1)
    return np.column_stack([X_ones, X1, X2])

X = create_data(X_room, X_lstat)
print(X)

[[ 1.000  6.575  4.980]
 [ 1.000  6.421  9.140]
 [ 1.000  7.185  4.030]
 ...
 [ 1.000  6.976  5.640]
 [ 1.000  6.794  6.480]
 [ 1.000  6.030  7.880]]


Зададим начальные параметры весов случайными числами от 0 до 1:

In [6]:
Theta = np.random.random_sample(size=(3, 1))
print(Theta)

[[ 0.168]
 [ 0.641]
 [ 0.770]]


Реализуем линейную функцию от наших параметров и данных (функция делает $N$ предсказаний по параметрам $\Theta$).

In [7]:
def linear_function(X, Theta):
    return np.dot(X, Theta) #X @ Theta

y_pred = linear_function(X, Theta)

In [8]:
print(X.shape)

(506, 3)


In [9]:
print(y_pred.shape)

(506, 1)
